### ISSUE TITLE
Css does not load on elm reactor

### ISSUE THREAD

**Issue by christian-predebon** [ahstro/elm-bulma-classes#2]
Hi @ahstro,
I'm trying to implement your package because I'm a huge fan of Bulma but I'm running into some trouble.
That's my `elm.json` file:
```json
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "ahstro/elm-bulma-classes": "3.1.0",
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0"
        },
        "indirect": {
            "elm/json": "1.1.3",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```
When I launch the `elm reactor` command and try to visit the localhost, I can see the HTML structure but without all the styles from Bulma.
I can't understand if I miss something so I hope you can help me.

Thank you.

**Comment by ahstro** [comment]
Hi @kasugaicrow :relaxed: 

This library is only to make it easier to use Bulma's classes in Elm (making sure nothing is misspelled, etc.), it doesn't actually import Bulma into your project, you still need to manually put their CSS into your project somehow. 

If you have any suggestions on how to make this clearer, feel free to create a PR :relaxed:
